apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
          - containerPort: 80
          env:
          - name: WELCOME_MSG
            valueFrom:
              configMapKeyRef:
                name: nginx-config
                key: WELCOME_MSG
          - name: APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: PASSWORD